---

- name: update hosts file
  lineinfile:
    path: /etc/hosts
    state: present
    regexp: '^{{ ansible_default_ipv4.address }}'
    line: '{{ ansible_default_ipv4.address }} {{ ansible_hostname + "." + dnsSuffix }} {{ ansible_hostname }}'
